### PR TITLE
Fix 'this.stops is not a function' error

### PR DESCRIPTION
**Pull request by imtheu**
Captura de tela de 2020-06-18 20-56-33

It can be tested in the "toggle like" tab in the Storybook. :)

Caused by https://github.com/felippenardi/lottie-react-web/commit/a9a236acc484d042d0f26d35cabf1f0a27a4e639

### CODE REVIEW

**Review by Kegulf — APPROVED** [review]

**Comment by ITLight** [comment]
You have missed one at line 41. It still running this.stops()

**Comment by samklonaris** [comment]
What's the status of this?

**Review by harusurv — COMMENTED** [review]
Works
